### ISSUE TITLE
run error  

### ISSUE THREAD

**Issue by V1rtualLife** [cxh0519/threestudio-gaussiandreamer#14]
在执行代码是报错，在原threestudio中并未见过类似的错误，不知道如何修改。望指点，谢谢
Traceback (most recent call last):
  File "/root/thre/three/Launch.py", line 305, in <module>
    main(args, extras)
  File "/root/thre/three/Launch.py", line 244, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1030, in _run_stage
    self.fit_loop.run()
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 252, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/manual.py", line 94, in run
    self.advance(kwargs)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/manual.py", line 114, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 311, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/root/thre/three/custom/threestudio-gaussiandreamer/system/gaussian_splatting.py", line 58, in training_step
    out = self(batch)
  File "/root/miniconda/envs/dream/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/thre/three/custom/threestudio-gaussiandreamer/system/gaussian_splatting.py", line 50, in forward
    outputs = self.renderer.batch_forward(batch)
  File "/root/thre/three/custom/threestudio-gaussiandreamer/renderer/gaussian_batch_renderer.py", line 38, in batch_forward
    render_pkg = self.forward(
  File "/root/thre/three/custom/threestudio-gaussiandreamer/renderer/diff_gaussian_rasterizer.py", line 148, in forward
    rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by hangsong06** [comment]
我遇到了和你一样的报错，请问你怎么解决的呀？
